### ISSUE TITLE
UnsupportedOperationException: Error: operation not supported if node not fully expanded

### ISSUE THREAD

**Issue by ngocdaothanh** [inejc/mcts#3]
In io.github.nejc92.mcts.MctsTest, after I change `NUMBER_OF_ITERATIONS` from 700 to 7, there will be error:

```
java.lang.UnsupportedOperationException: Error: operation not supported if node not fully expanded

	at io.github.nejc92.mcts.Mcts.validateBestChildComputable(Mcts.java:87)
	at io.github.nejc92.mcts.Mcts.getNodesMostPromisingAction(Mcts.java:94)
	at io.github.nejc92.mcts.Mcts.uctSearchWithExploration(Mcts.java:37)
	at io.github.nejc92.mcts.MctsTest.playOneTicTacToeGame(MctsTest.java:31)
	at io.github.nejc92.mcts.MctsTest.testUctSearch(MctsTest.java:23)
```

Is this a bug?

**Comment by inejc** [comment]
This is the expected behavior. The root node has to be expanded and all children visited in order to be able to return the most promising action of that node. The number of iterations has to be high enough that this is true for the current root node.

**Comment by ngocdaothanh** [comment]
Is `NUMBER_OF_ITERATIONS` the number of possible actions from a node?

For Tictactoe, there are only at most 9 possible actions. Why is it set to 700?

**Comment by inejc** [comment]
I suggest reading [A Survey of Monte Carlo Tree Search Methods](http://mcts.ai/pubs/mcts-survey-master.pdf). It should clear things up re the `NUMBER_OF_ITERATIONS` and the `EXPLORATION_PARAMETER`.
